name: "Default CodeQL Configuration for the Wave"

# Includes remote and local sources of taint
threat-models: local

queries:
  - name: Expands analysis to use the built-in security-extended suite
    uses: security-extended
  
packs:
  # For Java and Kotlin analysis
  #  - Use an external package:query (precompiled and hosted on the GitHub package registy)
  java:          
    - forrester-wave-demo-q3-2025/codeql-custom-java:WaveSqlTainted.ql

query-filters:
  # Exclude the default SQL Injection query to replace with the above
  - exclude:
      id: java/sql-injection